//===-- TabularInterfaces.td - Tabular interfaces ----------*- tablegen -*-===//
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef TABULAR_DIALECT_TABULAR_IR_TABULARINTERFACES
#define TABULAR_DIALECT_TABULAR_IR_TABULARINTERFACES

include "mlir/IR/OpBase.td"

#endif // TABULAR_DIALECT_TABULAR_IR_TABULARINTERFACES
