//===-- LinalgTransformOps.td - Python bindings -----------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===---------------------------------------------------------------------===//
//
// This is a base tablegen file for generating Python bindings for operations
// from the LinalgTransform dialect.
//
//===---------------------------------------------------------------------===//

#ifndef PYTHON_BINDINGS_LINALGTRANSFORM_OPS
#define PYTHON_BINDINGS_LINALGTRANSFORM_OPS

include "Dialects/LinalgTransform/LinalgTransformOps.td"
include "mlir/Bindings/Python/Attributes.td"

#endif // PYTHON_BINDINGS_LINALGTRANSFORM_OPS
