name: IREE Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: IREE Build and Test (Release Asserts)
    runs-on: ubuntu-20.04
    env:
      LLVM_SYMBOLIZER_PATH: /usr/lib/llvm-11/bin/llvm-symbolizer
    steps:
    - name: Set up Python
      uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # v4.3.0
      with:
        python-version: 3.9

    - name: Checkout project
      uses: actions/checkout@v3
      with:
        path: sandbox
        submodules: recursive

    - name: Install Python depends
      run: |
        python -m pip install -r ${GITHUB_WORKSPACE}/sandbox/requirements.txt

    - name: Install Ninja
      uses: llvm/actions/install-ninja@6a57890d0e3f9f35dfc72e7e48bc5e1e527cdd6c # Jan 17

    - name: Ccache for C++ compilation
      uses: hendrikmuhs/ccache-action@621a41397ed83711c72862638d9ff6e63fca3041 # v1.2.3
      with:
        key: ${{ runner.os }}-buildtestasserts
        # LLVM needs serious cache size
        max-size: 6G

    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}/sandbox
        python configure.py
        ccache -s
        echo "IREE_LLVM_SANDBOX_BUILD_DIR=${GITHUB_WORKSPACE}/sandbox/build" >> $GITHUB_ENV

    - name: Test
      run: |
        cd ${GITHUB_WORKSPACE}/sandbox
        python run_tests.py
