//===-- Passes.td - Transformation passes from TritonGPU ---*- tablegen -*-===//
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef STRUCTURED_DIALECT_TRITONGPU_PASSES
#define STRUCTURED_DIALECT_TRITONGPU_PASSES

include "triton/Dialect/TritonGPU/Transforms/Passes.td"

#endif // STRUCTURED_DIALECT_TRITONGPU_PASSES
